# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-29 22:57
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20160623_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=ckeditor.fields.RichTextField(default='Property Rep Professionals LLC.'),
            preserve_default=False,
        ),
    ]
