# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaillistcreator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='email_attachments')),
            ],
        ),
        migrations.AlterField(
            model_name='contactfile',
            name='docfile',
            field=models.FileField(upload_to='contactlists'),
        ),
    ]
