# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 16:29
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emaillistcreator', '0005_auto_20160430_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='docfile',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/'), upload_to='email_attachments'),
        ),
    ]
