# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('body', models.CharField(max_length=10000)),
            ],
        ),
    ]
