# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-17 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templatecreator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(),
        ),
    ]
