# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-25 21:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('templatecreator', '0002_auto_20160417_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
